const SNAKE_MAX_HEALTH = 100;
const SNAKE_STARTER_SIZE = 3;
const BOARD_WIDTH = 7;
const BOARD_HEIGHT = 7;
const BOARD_SIZE_SMALL = 7;
const BOARD_SIZE_MEDIUM = 11;
const BOARD_SIZE_LARGE = 19;
const BOARD_FOOD_SPAWN_CHANCE = 15;
const BOARD_MINIMUM_FOOD = 1;

module.exports = {
  SNAKE_MAX_HEALTH,
  SNAKE_STARTER_SIZE,
  BOARD_WIDTH,
  BOARD_HEIGHT,
  BOARD_SIZE_SMALL,
  BOARD_SIZE_MEDIUM,
  BOARD_SIZE_LARGE,
  BOARD_FOOD_SPAWN_CHANCE,
  BOARD_MINIMUM_FOOD
};